### ISSUE TITLE
spawn progress update doesn't update til end

### ISSUE THREAD

**Issue by oneilsh** [oneilsh/dsosuk8s#18]
Same as https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1090

Happened when I changed something about nginx-ingress and websockets...

**Comment by oneilsh** [comment]
fixed by https://github.com/oneilsh/dsosuk8s/commit/ae058e3d77de451a0c8efb2075ffa1ef3a22ec4e (change in values.yaml file, other file not related)

**Comment by NarekA** [comment]
Thanks for taking the time to document this issue. If anyone is not using Helm, we were having the same problem and we were able to fix by setting `proxy_buffering off;` in my `nginx.conf`.
